version: '3'

services:

  redis:
    image: redis:latest
    hostname: redis-db
    networks:
      - proxy-net
    container_name: redis-instance
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    ports:
      - 6379:6379

  redis-proxy-http:
    environment:
      - PROXY_HOST=0.0.0.0
      - PROXY_PORT=8080
      - CLIENT_HOST=redis-db
      - CLIENT_PORT=6379
      - CACHE_CAPACITY=10
      - CACHE_EXPIRY=10
      - CONCURRENT_MAX=2
    build:
      context: .
      dockerfile: http.Dockerfile
    depends_on:
      - redis
    hostname: redis-proxy-http
    container_name: redis-proxy-http
    networks:
      - proxy-net
    links:
      - redis:db
    ports:
      - 8080:8080

  redis-proxy-resp:
    build:
      context: .
      dockerfile: resp.Dockerfile
    depends_on:
      - redis
    hostname: redis-proxy-resp
    container_name: redis-proxy-resp
    environment:
      - PROXY_HOST=0.0.0.0
      - PROXY_PORT=6380
      - CLIENT_HOST=redis-db
      - CLIENT_PORT=6379
      - CACHE_CAPACITY=10
      - CACHE_EXPIRY=10
      - CONCURRENT_MAX=2
    networks:
      - proxy-net
    links:
      - redis:db
    ports:
      - 6380:6380


networks:
  proxy-net:
    external: true
    name: proxy-net