version: '3'

services:

  redis:
    image: redis:latest
    hostname: redis-db
    networks:
      - proxy-net
    container_name: redis-instance
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    expose:
      - 6379

  redis-proxy-http:
    build:
      context: .
      dockerfile: http.Dockerfile
    depends_on:
      - redis
    hostname: redis-proxy-http
    container_name: redis-proxy-http
    networks:
      - proxy-net
    links:
      - redis:db
    ports:
      - 80:80

  redis-proxy-resp:
    build:
      context: .
      dockerfile: resp.Dockerfile
    depends_on:
      - redis
    hostname: redis-proxy-resp
    container_name: redis-proxy-resp
    networks:
      - proxy-net
    links:
      - redis:db
    ports:
      - 6379:6380

networks:
  proxy-net:
    external: true